# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartInterphone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartInterphone

pod 'Alamofire', '~> 4.3'
pod 'SwiftyJSON', '~> 4.0'
pod 'CalendarKit'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Kingfisher'
pod 'GoogleSignIn'
pod 'JTAppleCalendar'
end
